# Basic Information 
title: Zheyi Yang
position: Ph.D. student
affiliation: ENSTA Paris
affiliation_link: https://uma.ensta-paris.fr
# affiliation_logo: 
email: zheyi(dot)yang (at) inria.fr

# Search Engine Optimization (SEO)
keywords: zheyi yang, yang zheyi, zheyiyang, yangzheyi
canonical: https://uma.ensta-paris.fr/~zheyi.yang
description: Zheyi Yang is a Ph.D. student at Ensta Paris. His research lies in diffusion MRI simulations and microstructural imaging.

# The option is used to enable the Johns Hopkins template.
# enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?user=a80R7JcAAAAJ
cv_link: ./assets/cv/Zheyi_Yang_CV_en.pdf
github_link: https://github.com/tapudodo/
linkedin: https://www.linkedin.com/in/zheyi-yang-a97619120/
# twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./assets/img/avatar.jpg
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
